---
- hosts: UDA
  tasks:
    - debug: var=ansible_facts
    - name: test CentOS connections
      net_ping:
      register: pingout
      when: ansible_facts['distribution'] == "CentOS"
    - name: test Windows connection
      win_ping:
      register: pingout
      when: ansible_facts['distribution'].find("Windows") != -1
    - debug: msg="{{ pingout }}"