---
- hosts: UDA
  tasks:
    - debug: var=ansible_facts
    - name: test CentOS connections
      ping:
      register: pingout
      when: ansible_facts['distribution'] == "CentOS"
    - name: test Windows connection
      win_ping:
      register: pingout
      when: ansible_facts['distribution'].find("Windows") != -1
    - debug: msg="{{ pingout }}"
    - name: view CentOS Services
      service_facts:
      register: src_facts
      when: ansible_facts['distribution'] == "CentOS"
    - name: view Windows Services
      win_shell: Get-Service
      register: src_facts
      when: ansible_facts['distribution'].find("Windows") != -1  
    - debug: msg="{{ src_facts }}"
    