---
- hosts: UDA
  tasks:
  - name: ensure apache is at the latest version
    service_facts:
    debug:
      var: ansible_facts.services
    when: "ansible_facts['distribution'] == \"CentOS\""